### ISSUE TITLE
Live Display Feature

### ISSUE THREAD

**Issue by masterkyle** [aquaris-dev/DEPRECATED_android_device_bq_vegetalte#6]
Hi,

i really miss the Live-Display function . It was very helpful in cm 12.1 but in cm13 i cant find it anymore :(
Is it a bug?

Thank you for your support :)

**Comment by eloimuns** [comment]
Can you provide logs please?

adb logcat > log.txt

Thanks!

**Comment by Kra1o5** [comment]
Hi @masterkyle ,

This will be fixed in today nightly.

Greetings
